### ISSUE TITLE
Spaces in volume name create config file with unsupported name

### ISSUE THREAD

**Issue by chrisvigil** [Venom1991/refind-btrfs#15]
My manual boot stanza originally contained a functional manual boot stanza containing the line `volume    "Arch Linux"`

This lead to the creation of the override file named "arch linux_vmlinuz-linux.conf" and the line `include btrfs-snapshot-stanzas/arch linux_vmlinuz-linux.conf`

The space in the file name caused refind to not include the file and thus the generated manual boot stanza did not show up in the rEFInd menu.

I was able to resolve my issue by changing the volume name to "Arch"  but refind-btrfs should probably make sue not to create file names unsupported by rEFInd.

**Comment by Venom1991** [comment]
Nice catch!  
Yeah, I'll just replace the white-space characters (if any) with underscores.

**Comment by Venom1991** [comment]
Fixed in release [0.3.11](https://github.com/Venom1991/refind-btrfs/releases/tag/v0.3.11).
