### ISSUE TITLE
Could not find the ESP!

### ISSUE THREAD

**Issue by richiq** [Venom1991/refind-btrfs#16]
Not sure what i should include here besides this. ESP is mounted for sure
```
$ sudo /usr/bin/refind-btrfs
Initializing the block devices using lsblk.
Initializing the physical partition table for device '/dev/sda' using lsblk.
Initializing the live partition table for device '/dev/sda' using findmnt.
Initializing the physical partition table for device '/dev/sdb' using lsblk.
Initializing the live partition table for device '/dev/sdb' using findmnt.
ERROR (refind_btrfs.state_management.conditions/conditions.py/check_filtered_block_devices): Could not find the ESP!
```
Feel free to ask any info about my setup

**Comment by Venom1991** [comment]
I'll need the output of the following commands:
```
lsblk --json --merge --paths --output NAME,TYPE,MAJ:MIN
lsblk /dev/sda --json --paths --tree --output PTUUID,PTTYPE,PARTUUID,PARTTYPE,PARTLABEL,UUID,NAME,FSTYPE,LABEL,MOUNTPOINT
lsblk /dev/sdb --json --paths --tree --output PTUUID,PTTYPE,PARTUUID,PARTTYPE,PARTLABEL,UUID,NAME,FSTYPE,LABEL,MOUNTPOINT
```

**Comment by Venom1991** [comment]
I've just release an implementation of this proposed feature, tried it locally and I've been able to identify the ESP by setting its UUID in the config file. By default this option is set to an empty UUID and thus ignored.

You can try setting the option "esp_uuid" (first one listed in the file) to "ed31ab35-a36e-8341-b60e-40977b4e66c0" and report back here with the results.

**Comment by richiq** [comment]
I set esp_uuid and after that the stanzas started to generate, became bootable and everything works as expected. Thanks for the great work on this must-have tool!

**Comment by Venom1991** [comment]
That's just great, I'm glad it finally worked out for you!
