### ISSUE TITLE
/usr/bin/python: No module named refind_btrfs

### ISSUE THREAD

**Issue by mizzunet** [Venom1991/refind-btrfs#25]
I just had a system update of around 1GB, after that, ` refind-btrfs` seems fails to run. I tried uninstalling and reinstalling it several times

```
 ~  refind-btrfs
/usr/bin/python: No module named refind_btrfs
```

**Comment by Venom1991** [comment]
I still haven't updated my system but I'm aware that Python 3.10 just got released and every AUR package needs to be rebuilt and reinstalled.
Have a look here - https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/

**Comment by mizzunet** [comment]
Oh, that maybe why I had to reinstalled some other AUR packages like anki, gtg etc

**Comment by mizzunet** [comment]
> By the way, this is potentially only a packaging issue and you should probably ask this question on the corresponding AUR package's page.

Alright :+1:

**Comment by mizzunet** [comment]
I have manually built it, now it's working.

**Comment by Venom1991** [comment]
I've added a list of dependent packages which need to be rebuilt manually in a pinned [comment](https://aur.archlinux.org/packages/refind-btrfs/#pinned-841050).
