### ISSUE TITLE
Prevent refind-btrfs from including other kernel snapshots and changing snapshot icon

### ISSUE THREAD

**Issue by ShabirK21** [Venom1991/refind-btrfs#35]
I have 3 kernels installed on my system with refind-btrfs service running. I only want the default kernel snapshots to be included in refind and not include the other two. I tried commenting out the kernels in refind.conf but it just regenerated and also I want to change the icon of the snapshots, but when a new snapshot it found, it resets the icon to my kernel icon.

**Comment by Venom1991** [comment]
Regarding the icon issues - you might want to check the value of [this](https://github.com/Venom1991/refind-btrfs/blob/master/src/refind_btrfs/data/refind-btrfs.conf-sample#L158) option. I suppose it should be set to "custom", in your case.

Exclusion of found boot stanzas and the generation of their snapshot boot stanzas is currently not supported. I have an idea about this feature's implementation but I simply don't have the time to work on it. Maybe in a couple of weeks or so.

**Comment by ShabirK21** [comment]
Alright, thanks for the good work!

**Comment by Venom1991** [comment]
Implemented in release [0.5.0](https://github.com/Venom1991/refind-btrfs/releases/tag/v0.5.0).
