### ISSUE TITLE
fstab inline comments handled incorrectly

### ISSUE THREAD

**Issue by UltraBlackLinux** [Venom1991/refind-btrfs#38]
Fstab lines containing a comment after valid fstab contents will cause refind-btrfs to not recognize the partitions as valid:
```
ERROR: None of the matched boot stanzas can be combined with any of the prepared snapshots!
```
See #37

**Comment by Venom1991** [comment]
Fixed in release [0.5.0](https://github.com/Venom1991/refind-btrfs/releases/tag/v0.5.0).
