### ISSUE TITLE
No newline between generated includes in `refind.conf`

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Venom1991/refind-btrfs#4]
This issue was identified in [issue 3](https://github.com/Venom1991/refind-btrfs/issues/3). When multiple includes are generated **refind-btrfs** adds the all on the same line, causing them to not be included.

**Comment by Venom1991** [comment]
Thanks, I'll fix this when I can but you shouldn't encounter any problems regarding this bug as you've fixed the config file yourself.

**Comment by Venom1991** [comment]
Fixed in release [0.2.17](https://github.com/Venom1991/refind-btrfs/releases/tag/v0.2.17).

**Comment by Th3Whit3Wolf** [comment]
Unrelated but I wanted you to know I added an entry for this program in the ArchWiki [Snapper](https://wiki.archlinux.org/index.php/Snapper#Wrapping_pacman_transactions_in_snapshots) and [Btrfs](https://wiki.archlinux.org/index.php/Btrfs#Booting_into_snapshots) pages so you may get some more users.

**Comment by Venom1991** [comment]
> Unrelated but I wanted you to know I added an entry for this program in the ArchWiki [Snapper](https://wiki.archlinux.org/index.php/Snapper#Wrapping_pacman_transactions_in_snapshots) and [Btrfs](https://wiki.archlinux.org/index.php/Btrfs#Booting_into_snapshots) pages so you may get some more users.

Thank you for doing that, I've been meaning to do it myself but I believe only (mostly) stable software belongs there and I'm not really sure my tool is entirely stable.

But then again, how can it reach stability if nobody knows about it or its bugs? :thumbsup:

**Comment by Th3Whit3Wolf** [comment]
I agree. I think people being more aware of this project will get more people (and hopefully developers) using rEFInd. I really wish it was the defacto linux bootloader instead of GRUB.

**Comment by Venom1991** [comment]
> I agree. I think people being more aware of this project will get more people (and hopefully developers) using rEFInd. I really wish it was the defacto linux bootloader instead of GRUB.

Judging by [this](https://en.wikipedia.org/wiki/Comparison_of_boot_loaders#Features), GRUB is quite a bit more feature complete than rEFInd which makes sense because the latter focuses primarily (or even solely) on (U)EFI systems.
Anyway, I don't think GRUB is going to be replaced by rEFInd (or any other competing boot loader / boot manager) anytime soon.
Still, if one owns an (U)EFI system (they probably do, in 2021) then rEFInd is definitely the way to go. It's great software.
