### ISSUE TITLE
Manual boot stanza

### ISSUE THREAD

**Issue by Walrusz** [Venom1991/refind-btrfs#40]
Hello, previously I've been using rEFInd with only auto detection and having a refind_linux.conf in the boot directory. When I tried to run refind-btrfs I got an error saying it `Could not find a boot stanza matched with the root partition`. Can I use it without a manual boot stanza or is it required to set one up?

**Comment by Venom1991** [comment]
A manual boot stanza is one of the [prerequisites](https://github.com/Venom1991/refind-btrfs#prerequisites) but it shouldn't be too much work to write [one](https://github.com/Venom1991/refind-btrfs#example) yourself.
