### ISSUE TITLE
No module named refind_btrf

### ISSUE THREAD

**Issue by coffseducation** [Venom1991/refind-btrfs#57]
Run installation script.

"No module named refind_btrf"

 
         bandicoot@arcoplasm
                   ooo:                     -------------------
                  yoooo/                    OS: ArcoLinux x86_64
                 yooooooo                   Host: TM1701
                yooooooooo                  Kernel: 6.8.8-arch1-1
               yooooooooooo                 Uptime: 6 mins
             .yooooooooooooo                Packages: 2110 (pacman)
            .oooooooooooooooo               Shell: bash 5.2.26
           .oooooooarcoooooooo              Resolution: 1920x1080
          .ooooooooo-oooooooooo             DE: Plasma 6.0.4
         .ooooooooo-  oooooooooo            WM: kwin
        :ooooooooo.    :ooooooooo           Theme: Arc-Dark [GTK2/3]
       :ooooooooo.      :ooooooooo          Icons: kora [GTK2/3]
      :oooarcooo         .oooarcooo         Terminal: konsole
     :ooooooooy           .ooooooooo        CPU: Intel i7-8550U (8) @ 4.000GHz
    :ooooooooo   /ooooooooooooooooooo       GPU: NVIDIA GeForce MX150
   :ooooooooo      .-ooooooooooooooooo.     GPU: Intel UHD Graphics 620
  ooooooooo-             -ooooooooooooo.    Memory: 3.10GiB / 15.51GiB (20%)
 ooooooooo-                 .-oooooooooo.   GPU Driver: i915
ooooooooo.                     -ooooooooo   CPU Usage: 22%
                                            Disk (/): 15G / 220G (7%)
                                            Font: Noto Sans, 10 [GTK2/3]

[bandicoot@arcoplasm ~]$ journalctl -u refind-btrfs -b
May 02 09:51:33 arcoplasm systemd[1]: Starting Generate rEFInd manual boot stanzas from Btrfs snapshots...
May 02 09:51:33 arcoplasm python[676]: /usr/bin/python: No module named refind_btrfs
May 02 09:51:33 arcoplasm systemd[1]: refind-btrfs.service: Main process exited, code=exited, status=1/FAILURE
May 02 09:51:33 arcoplasm systemd[1]: refind-btrfs.service: Failed with result 'exit-code'.
May 02 09:51:33 arcoplasm systemd[1]: Failed to start Generate rEFInd manual boot stanzas from Btrfs snapshot>
...skipping...
May 02 09:51:33 arcoplasm systemd[1]: Starting Generate rEFInd manual boot stanzas from Btrfs snapshots...
May 02 09:51:33 arcoplasm python[676]: /usr/bin/python: No module named refind_btrfs
May 02 09:51:33 arcoplasm systemd[1]: refind-btrfs.service: Main process exited, code=exited, status=1/FAILURE
May 02 09:51:33 arcoplasm systemd[1]: refind-btrfs.service: Failed with result 'exit-code'.
May 02 09:51:33 arcoplasm systemd[1]: Failed to start Generate rEFInd manual boot stanzas from Btrfs snapshot>
~

[bandicoot@arcoplasm ~]$ systemctl status refind-btrfs
× refind-btrfs.service - Generate rEFInd manual boot stanzas from Btrfs snapshots
     Loaded: loaded (/usr/lib/systemd/system/refind-btrfs.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Thu 2024-05-02 09:51:33 AEST; 10min ago
    Process: 676 ExecStart=/usr/bin/python -m refind_btrfs --run-mode background (code=exited, status=1/FAILU>
   Main PID: 676 (code=exited, status=1/FAILURE)
        CPU: 48ms

May 02 09:51:33 arcoplasm systemd[1]: Starting Generate rEFInd manual boot stanzas from Btrfs snapshots...
May 02 09:51:33 arcoplasm python[676]: /usr/bin/python: No module named refind_btrfs
May 02 09:51:33 arcoplasm systemd[1]: refind-btrfs.service: Main process exited, code=exited, status=1/FAILURE
May 02 09:51:33 arcoplasm systemd[1]: refind-btrfs.service: Failed with result 'exit-code'.
May 02 09:51:33 arcoplasm systemd[1]: Failed to start Generate rEFInd manual boot stanzas from Btrfs snapshot>
lines 1-12/12 (END)

**Comment by Venom1991** [comment]
I don't know about Arco but on Arch, in case Python received an update, all of the AUR packages written in Python have to be rebuilt. I'd try that, if I were you. Otherwise, since I'm not using Arco I don't know exactly how it's integrated with AUR or if at all. Perhaps they provide the `refind-btrfs` package in their own repositories, prebuilt?

**Comment by coffseducation** [comment]
Thanks.
